// Danh sách ngân hàng Việt Nam (dùng cho gợi ý ô "Ngân hàng").
// Người dùng vẫn có thể tự gõ tên khác không có trong danh sách.
export const VN_BANKS = [
  'Vietcombank',
  'VietinBank',
  'BIDV',
  'Agribank',
  'Techcombank',
  'MB Bank',
  'ACB',
  'Sacombank',
  'VPBank',
  'TPBank',
  'VIB',
  'HDBank',
  'SHB',
  'OCB',
  'MSB',
  'Eximbank',
  'SeABank',
  'LPBank',
  'Nam A Bank',
  'KienlongBank',
  'VietBank',
  'PVcomBank',
  'Bac A Bank',
  'ABBank',
  'NCB',
]
